### ISSUE TITLE
Website Is Frozen

### ISSUE THREAD

**Issue by Raxtus76** [SAXTEN2011/URLGoldCounter#1]
I can't interact with the site in anyway. I think it started when I tried to save a new gold value, but I'm not positive. I can't save changes, delete the character, click on stam/gold/actions, etc. The problem persists even when I attempt to make a new tab. The site was working fine this afternoon(July 5th).

**Comment by SAXTEN2011** [comment]
This is likely because one of your characters has spaces in their name, a fix is being worked on this issue
